### ISSUE TITLE
Project Photos

### ISSUE THREAD

**Issue by objectiveSee** [MFornander/LightSwarm#17]
Hey! I came across your repo while searching for projects that had used the ESP8266 + mesh networking at the burn. I'd love to see some photos if you have a link to your final project. I am also curious to hear if you had any issues w/ mesh networking as I am designing a project that would require 10-20 connected nodes with synced LED animations. Thanks!!

**Comment by MFornander** [comment]
This is a movie of a bench power test with six ESPs driving a total of 24 tentacles.  We had five portable 8ft "dongs" sticking up on bicycles, all in sync too:
https://www.facebook.com/groups/717748685076630/permalink/724183724433126/

**Comment by MFornander** [comment]
Dong test here:
https://www.facebook.com/jc.ebert/videos/10211179810025091/

**Comment by MFornander** [comment]
Sync video:
https://www.facebook.com/rolf.kirby/videos/10154702708152507/

**Comment by MFornander** [comment]
Dong Sync:
https://www.facebook.com/jc.ebert/videos/10211283437215706/

**Comment by objectiveSee** [comment]
hey @MFornander! Sorry for slow reply! I am super excited about your photos because my project is almost identical! We are building LED bike poles for our campmates (minus the fur... though now that I've seen fur... who knows!). Here's a pic of the poles 2 of our mates had last year. Our goal is to have bikes that will light up in unison and trigger Green/Yellow/Red lights when our group needs to stop for something! I'd love to hear about your experiences with the mesh and whether it was reliable. Would you be free to chat sometime?

<img width="619" alt="screen shot 2018-04-02 at 3 37 04 pm" src="https://user-images.githubusercontent.com/1684106/38266311-565c9294-3746-11e8-8c2a-0f633281a1f3.png">
