### ISSUE TITLE
Build Squidlets

### ISSUE THREAD

**Issue by Phrogz** [MFornander/LightSwarm#6]
6 squidlets, each containing

* A brain
* A box for a body
* An antenna
* 4 LED connectors

**Comment by Phrogz** [comment]
@MFornander @JustinEbert I couldn't see from the video; is this task done? Or do the squidlets still need boxes around them?

**Comment by MFornander** [comment]
YEah we need some kind of box, or at least cable protection.  I could be convinced we just mount them in the open for easy access though.  Thoughts?

**Comment by Phrogz** [comment]
Apogaea is forecast to have rain all this week. If the car is water-proof, and Colorado dust non-conductive, then I think we can leave without box for Apogaea. Otherwise, der squid need boxen.

**Comment by MFornander** [comment]
Boxes it is!

**Comment by MFornander** [comment]
Done
